### ISSUE TITLE
Markdown in paginated pages are not rendered

### ISSUE THREAD

**Issue by UlyssesZh** [sverrirs/jekyll-paginate-v2#256]
```markdown
---
layout: home
pagination: 
  enabled: true
---

**test**
```

Rendered result:
![image](https://github.com/sverrirs/jekyll-paginate-v2/assets/26196187/07afd0e0-f0d5-457d-bfdf-87ea39a53b16)

The result if `pagination` in the frontmatter is commented out:
![image](https://github.com/sverrirs/jekyll-paginate-v2/assets/26196187/64e2db44-ca29-4d36-9279-bb578495cb80)

**Comment by UlyssesZh** [comment]
Noticed that this should have been fixed in master. We just need to wait for a new release.

**Comment by CookiePLMonster** [comment]
Unfortunately this fix still doesn't see an official release in 2025.
